# Generated by Django 4.0.6 on 2022-09-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckOut',
            new_name='Cart',
        ),
    ]
