# Generated by Django 4.0.6 on 2022-09-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_rename_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
    ]
